@startuml
'Источник: Горелая Н.В. Организация кредитования в коммерческом банке. М., 2014. С. 21.

(*) --> "Поступление от клиента заявки на кредит"
 --> "Оценка и анализ кредитоспособности заемщика"
 --> "Оценка обеспечения возвратности кредита"
 --> "Подготовка досье заемщика к заседанию кредитного комитета"
 if "Решение кредитного комитета" then
   --> [false] "Отказ"
 else
   --> [true] "Выдача кредита"
   --> "Мониторинг"
   --> "Погашение кредита"
 endif

 "Погашение кредита" --> (*)
 "Отказ" --> (*)
 "Мониторинг" --> "Работа с проблемной задолженностью"
 "Работа с проблемной задолженностью" --> "Погашение кредита"


@enduml