@startuml

(*) --> "Получение заявки на кредит"
 --> "Оценка заявки на кредит (Скоринг)"

 if "Решение" then
    --> [false] Отказ
    --> (*)
 else
    --> [true] Одобрение
    --> "Формирование предложения"
    -->(*)

@enduml